### ISSUE TITLE
RP2040 flash content verification error

### ISSUE THREAD

**Issue by elpiel** [embassy-rs/teleprobe#4]
Trying to flash using a picoprobe to another pico a simple `blinky` example, I get an error:

`Flash content verification failed.`

Sadly, due to #3 it does not show any debug logging from `probe-rs` with `RUST_LOG=debug`.

After trying to flash with `teleprobe`, I also get an error using `probe-run` and even after `BOOTSEL` it manages to flash the `blinky` once and then still gives out this verification error and corrupts `probe-run` flashing too (requiring `BOOTSEL` on power up).

```
Error: A ARM specific error occured.

Caused by:
    Timeout occured during operation.
```

**Comment by Dirbaio** [comment]
if you weren't running from RAM, it might've been fixed by https://github.com/embassy-rs/teleprobe/commit/e378ade7b57ed49c8c38936d178e6d52651e6f67. Can you check again?

**Comment by elpiel** [comment]
Yes, I'm not running the app from RAM.

I did try the new fixes, however, they still don't work. I've added `context` (from anyhow) to see where it breaks and it still at the same place.

Afterwards, trying to flash with `probe-run` gives the same timeout error.

This time I got a backtrace if it would help:

```
Stack backtrace:
   0: <E as anyhow::context::ext::StdError>::ext_context
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.71/src/context.rs:27:29
   1: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.71/src/context.rs:54:31
   2: teleprobe::run::Runner::new
             at /mnt/Disk/Projects/lechev.space/teleprobe/src/run.rs:149:13
   3: teleprobe::run::run
             at /mnt/Disk/Projects/lechev.space/teleprobe/src/run.rs:40:17
   4: teleprobe::async_main::{{closure}}
             at /mnt/Disk/Projects/lechev.space/teleprobe/src/main.rs:88:17
   5: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/local.rs:923:42
   6: tokio::task::local::LocalSet::with::{{closure}}
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/local.rs:684:13
   7: std::thread::local::LocalKey<T>::try_with
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/thread/local.rs:252:16
   8: std::thread::local::LocalKey<T>::with
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/thread/local.rs:228:9
   9: tokio::task::local::LocalSet::with
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/local.rs:667:9
  10: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/local.rs:913:9
  11: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/local.rs:573:18
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/core/src/future/future.rs:125:9
  13: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:541:57
  14: tokio::runtime::coop::with_budget
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
  15: tokio::runtime::coop::budget
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
  16: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:541:25
  17: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:350:19
  18: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:540:36
  19: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:615:57
  20: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
  21: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:615:27
  22: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:530:19
  23: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:154:24
  24: tokio::runtime::runtime::Runtime::block_on
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/runtime.rs:302:47
  25: tokio::task::local::LocalSet::block_on
             at /home/elpiel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/local.rs:534:9
  26: teleprobe::main
             at /mnt/Disk/Projects/lechev.space/teleprobe/src/main.rs:74:5
  27: core::ops::function::FnOnce::call_once
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/core/src/ops/function.rs:250:5
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/sys_common/backtrace.rs:134:18
  29: std::rt::lang_start::{{closure}}
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/rt.rs:166:18
  30: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/core/src/ops/function.rs:287:13
  31: std::panicking::try::do_call
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/panicking.rs:485:40
  32: std::panicking::try
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/panicking.rs:449:19
  33: std::panic::catch_unwind
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/panic.rs:140:14
  34: std::rt::lang_start_internal::{{closure}}
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/rt.rs:148:48
  35: std::panicking::try::do_call
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/panicking.rs:485:40
  36: std::panicking::try
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/panicking.rs:449:19
  37: std::panic::catch_unwind
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/panic.rs:140:14
  38: std::rt::lang_start_internal
             at /rustc/0599b6b931816ab46ab79072189075f543931cbd/library/std/src/rt.rs:148:20
  39: main
  40: __libc_start_main
             at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  41: _start

```
